#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Checking: Code Formatting before commit'

npm run format ||
(
    echo '❌ Run format commad failed ❌'
    false;
)

# Check Prettier standards
npm run check-format ||
(
    echo '❌ Prettier Check Failed. ❌
         Run npm run format, add changes and try commit again.';
    false;
)

# If everything passes... Now we can commit
echo '✅ Time To Push The Code ✅'